# Generated by Django 3.2 on 2021-05-08 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stark_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyandsell',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 16, 14, 857698), verbose_name='تاریخ و زمان'),
        ),
        migrations.AlterField(
            model_name='robotsubscription',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 16, 14, 857698), verbose_name='تاریخ و زمان خرید'),
        ),
        migrations.AlterField(
            model_name='robotsubscription',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 16, 14, 857698), verbose_name='تاریخ و زمان انقضا'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 16, 14, 857698), verbose_name='تاریخ و زمان'),
        ),
        migrations.AlterField(
            model_name='userstoke',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 16, 14, 857698), verbose_name='آخرین زمان ثبت دارایی'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='address',
            field=models.CharField(max_length=45, unique=True, verbose_name='آدرس کیف پول'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 16, 14, 857698), verbose_name='تاریخ و زمان خرید'),
        ),
        migrations.AlterField(
            model_name='walletorder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 16, 14, 857698), verbose_name='تاریخ و زمان'),
        ),
    ]
