# Generated by Django 3.2 on 2021-05-08 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stark_siteSetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifymodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 11, 16, 14, 857698), verbose_name='تاریخ و زمان'),
        ),
    ]
